type Query {
  """
  Получить данные клиента по идентификатору
  """
  client(id: ID!): Client
  
  """
  Получить список клиентов
  """
  clients(limit: Int, offset: Int): [Client]
}

"""
Клиент
"""
type Client {
  """
  Идентификатор клиента
  """
  id: ID!
  """
  Имя клиента
  """
  name: String!
  """
  Возраст клиента
  """
  age: Int!
  
  """
  Связанные с клиентом документы
  """
  documents: [Document!]!
  """
  Родственники клиента
  """
  relatives: [Relative!]!
}

"""
Документ клиента
"""
type Document {
  """
  Идентификатор клиента
  """
  id: ID!
  """
  Тип документа
  """
  type: String!
  """
  Номер документа
  """
  number: String!
  """
  Дата выдачи
  """
  issueDate: String!
  """
  Действителен до
  """
  expiryDate: String!
}

"""
Родственник клиента
"""
type Relative {
  """
  Идентификатор родственника
  """
  id: ID!
  """
  Степень родства
  """
  relationType: String!
  """
  Имя родственника
  """
  name: String!
  """
  Возраст родственника
  """
  age: Int!
}